prompts:
  - "What is the capital of France?"
  - "What is the capital of Bangladesh?"
  - "In which year did World War II end?"
  - "Who was the first president of the United States?"
  - "What is the largest planet in our solar system?"
  - "What is the currency of Japan?"
  - "Who wrote the play 'Romeo and Juliet'?"
  - "What is the tallest mountain in the world?"
  - "Write python programming code to add two numbers?"
  - "When did Albert Einstein win nobel prize?"


providers:
  - "ollama:gemma:2b":
      id: local-gemma
      label: "Gemma 2B (Local)"
      config:
        baseUrl: "http://localhost:11434"


  - "ollama:mistral:7b-instruct":
      id: local-mistral
      label: "Mistral 7B Instruct (Local)"
      config:
        baseUrl: "http://localhost:11434"


tests:
  - vars: {}